# Generated by Django 6.0 on 2026-04-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
